:name: icij-offshoreleaks
:long-name: Offshore Leaks Database by ICIJ
:description: The Offshore Leaks Database and guide from the International Consortium of Investigative Journalists (ICIJ)
:icon: documentation/img/icij-logo.png
:tags: example-data,dataset,fraud-data,data-leaks,offshoreleaks,panama-papers,offshoreleaksicij
:author: William Lyon
:demodb: false
:data: false
:use-load-script: false
:use-dump-file: data/icij-offshoreleaks-43.dump
:zip-file: false
:use-plugin: false
:target-db-version: 4.3
:bloom-perspective: bloom/icij-offshoreleaks.bloom-perspective
:guide: documentation/icij-offshoreleaks.neo4j-browser-guide
:rendered-guide: https://guides.neo4j.com/sandbox/icij-offshoreleaks/index.html
:model: documentation/img/datamodel.png
:example: documentation/img/example.png

:todo: false
image::{icon}[width=100]

== {long-name} Graph Example

Description: _{description}_

ifeval::[{todo} != false]
To Do: {todo}
endif::[]

.Model
image::{model}[]

.Example
image::{example}[width=600]

.Example Query:
[source,cypher,role=query-example,param-name=name,param-value="Ross, Jr. - Wilbur Louis",result-column=name,expected-result="WLR/TRF Shipping GP Ltd."]
----
MATCH (a:Officer {name:$name})-[r:officer_of|intermediary_of|registered_address*..10]-(b)
RETURN b.name as name LIMIT 20
----

=== Setup

This is for Neo4j version: {target-db-version}

ifeval::[{use-plugin} != false]
Required plugins: {use-plugin}
endif::[]

ifeval::[{demodb} != false]
The database is also available on https://demo.neo4jlabs.com:7473

Username "{name}", password: "{name}", database: "{name}"
endif::[]

Rendered guide available via: `:play {rendered-guide}`

Unrendered guide: link:{guide}[]

Load graph data via the following:

ifeval::[{data} != false]
==== Data files: `{data}`

Import flat files (csv, json, etc) using Cypher's https://neo4j.com/docs/cypher-manual/current/clauses/load-csv/[`LOAD CSV`], https://neo4j.com/labs/apoc/[APOC library], or https://neo4j.com/developer/data-import/[other methods].
endif::[]

ifeval::[{use-dump-file} != false]
==== Dump file: `{use-dump-file}`

* Drop the file into the `Files` section of a project in Neo4j Desktop. Then choose the option to `Create new DBMS from dump` option from the file options.

* Use the neo4j-admin tool to load data from the command line with the command below.

[source,shell,subs=attributes]
----
bin/neo4j-admin load --from {use-dump-file} [--database "database"]
----

* Upload the dump file to Neo4j Aura via https://console.neo4j.io/#import-instructions
endif::[]

ifeval::[{use-load-script} != false]
==== Data load script: `{use-load-script}`

[source,shell,subs=attributes]
----
bin/cypher-shell -u neo4j -p "password" -f {use-load-script} [-d "database"]
----

Or import in Neo4j Browser by dragging or pasting the content of {use-load-script}.
endif::[]

ifeval::[{zip-file} != false]
==== Zip file

Download the zip file link:{repo}/raw/master/{name}.zip[{name}.zip] and add it as "project from file" to https://neo4j.com/developer/neo4j-desktop[Neo4j Desktop^].
endif::[]

=== Code Examples

* link:code/javascript/example.js[JavaScript]
* link:code/java/Example.java[Java]
* link:code/csharp/Example.cs[C#]
* link:code/python/example.py[Python]
* link:code/go/example.go[Go]

=== GraphQL API

See link:graphql[`/graphql` directory] for Node.js GraphQL API server example using link:https://www.npmjs.com/package/@neo4j/graphql[`@neo4j/graphql`]

=== Feedback

Feel free to submit issues or pull requests for improvement on this repository.